# Generated by Django 4.0.4 on 2022-06-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Service Category'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='service_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Sub-Service Category'),
        ),
    ]
