# Generated by Django 4.0.4 on 2022-06-20 08:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('4ff3c581-b199-47b3-b177-3beddfada996'), editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, verbose_name='Email Address')),
                ('mobile', models.CharField(max_length=255, verbose_name='Phone Number')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('desc', models.CharField(max_length=255, verbose_name='Dec. Message')),
                ('is_active', models.BooleanField(default=True)),
                ('is_solved', models.BooleanField(default=False)),
            ],
        ),
    ]
