# Generated by Django 4.0.4 on 2022-06-23 07:05

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contactusquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusquery',
            name='id',
            field=models.UUIDField(default=uuid.UUID('520596bc-57de-42a9-86a1-55e588c461ff'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='professionaluserservice',
            name='estimate_time',
            field=models.CharField(max_length=255, null=True, verbose_name='Time to Complete'),
        ),
        migrations.AlterField(
            model_name='professionaluserservice',
            name='subservice_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), size=None),
        ),
    ]
