# Generated by Django 4.0.4 on 2022-07-18 06:11

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contactusquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusquery',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date query made'),
        ),
        migrations.AddField(
            model_name='contactusquery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date update made'),
        ),
        migrations.AlterField(
            model_name='contactusquery',
            name='id',
            field=models.UUIDField(default=uuid.UUID('152618c0-d988-4250-86e3-59d4b8c014aa'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='professionaluserservice',
            name='estimate_time',
            field=models.CharField(max_length=255, null=True, verbose_name='Time to Complete'),
        ),
        migrations.AlterField(
            model_name='professionaluserservice',
            name='payment_modes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='cash', max_length=30), size=None),
        ),
        migrations.AlterField(
            model_name='professionaluserservice',
            name='subservice_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Others')], default='male', max_length=25),
        ),
        migrations.CreateModel(
            name='UserRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('bae0fd05-857c-45cc-9043-595437a34424'), editable=False, primary_key=True, serialize=False)),
                ('descriptive_msg', models.TextField()),
                ('interested_prof', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date query made')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date update made')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subservice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subservice')),
            ],
        ),
        migrations.CreateModel(
            name='HireProfessionalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b4130bec-5099-4098-8d1a-3c4c4e945695'), editable=False, primary_key=True, serialize=False)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=25)),
                ('descriptive_msg', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date query made')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date update made')),
                ('prof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professionaluser')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlaggedProfessionalUserReport',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c665614f-4b07-45f3-9b46-20e937226fbc'), editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date query made')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date update made')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professionaluser')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteUser',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('9ebe37b4-0427-4dcd-a7f4-ad6ceed7d1fd'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date query made')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date update made')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professionaluser')),
            ],
        ),
    ]
